//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelpDesk.Lang.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add content.
        /// </summary>
        internal static string addcontent {
            get {
                return ResourceManager.GetString("addcontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string cnacleid {
            get {
                return ResourceManager.GetString("cnacleid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Comment.
        /// </summary>
        internal static string commentuser {
            get {
                return ResourceManager.GetString("commentuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        internal static string editid {
            get {
                return ResourceManager.GetString("editid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string emails {
            get {
                return ResourceManager.GetString("emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Img  The Problem.
        /// </summary>
        internal static string imgurl {
            get {
                return ResourceManager.GetString("imgurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the problem solved ?.
        /// </summary>
        internal static string LCx {
            get {
                return ResourceManager.GetString("LCx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log out.
        /// </summary>
        internal static string logout_b {
            get {
                return ResourceManager.GetString("logout_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype the password.
        /// </summary>
        internal static string PasswordsConffert {
            get {
                return ResourceManager.GetString("PasswordsConffert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGNUP.
        /// </summary>
        internal static string reg {
            get {
                return ResourceManager.GetString("reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        internal static string regis {
            get {
                return ResourceManager.GetString("regis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new account.
        /// </summary>
        internal static string RegPage {
            get {
                return ResourceManager.GetString("RegPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        internal static string savedid {
            get {
                return ResourceManager.GetString("savedid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Comment.
        /// </summary>
        internal static string SB {
            get {
                return ResourceManager.GetString("SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        internal static string SEnd {
            get {
                return ResourceManager.GetString("SEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for problem ?.
        /// </summary>
        internal static string Serarhbar1 {
            get {
                return ResourceManager.GetString("Serarhbar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YourProblme.
        /// </summary>
        internal static string Supject {
            get {
                return ResourceManager.GetString("Supject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TItle.
        /// </summary>
        internal static string Suptitle {
            get {
                return ResourceManager.GetString("Suptitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploud.
        /// </summary>
        internal static string uploud_b {
            get {
                return ResourceManager.GetString("uploud_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi :.
        /// </summary>
        internal static string yourname {
            get {
                return ResourceManager.GetString("yourname", resourceCulture);
            }
        }
    }
}
